<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXCuvzxv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXCuvzxv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXCuvzxv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXCuvzxv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXCuvzxv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XCuvzxv',
    'container.build_id' => 'aef6875c',
    'container.build_time' => 1619198598,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXCuvzxv');
