<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZA14Ruj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZA14Ruj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZA14Ruj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZA14Ruj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZA14Ruj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZA14Ruj',
    'container.build_id' => 'fa05d83d',
    'container.build_time' => 1619200618,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZA14Ruj');
